version: '3.8'

services:
  angular-app:
    image: node:18
    container_name: uvpa3.21
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install --force && npm install -g @angular/cli && ng serve --host 0.0.0.0"
